<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="2.414" timestamp="2022-10-11T16:30:40.706285" hostname="vorph-maison"><testcase classname="" name="tests.test_deploy_aml_model" time="0.000"><error message="collection failure">tests/test_deploy_aml_model.py:4: in &lt;module&gt;
    from azure_helper.steps.deploy_aml_model import DeploymentSettings, DeployModel
E   ModuleNotFoundError: No module named 'azure_helper.steps.deploy_aml_model'
        Mock       = &lt;class 'unittest.mock.Mock'&gt;
        Path       = &lt;class 'pathlib.Path'&gt;
        __builtins__ = &lt;builtins&gt;
        __cached__ = '/media/vorph/datas/perso/azure-mlops-helper/tests/__pycache__/test_deploy_aml_model.cpython-38.pyc'
        __doc__    = None
        __file__   = '/media/vorph/datas/perso/azure-mlops-helper/tests/test_deploy_aml_model.py'
        __loader__ = &lt;_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7f9e96289250&gt;
        __name__   = 'test_deploy_aml_model'
        __package__ = ''
        __spec__   = ModuleSpec(name='test_deploy_aml_model', loader=&lt;_pytest.assertion.rewrite.AssertionRewritingHook object at 0x7f9e96289250&gt;, origin='/media/vorph/datas/perso/azure-mlops-helper/tests/test_deploy_aml_model.py')</error><error message="collection failure">ImportError while importing test module '/media/vorph/datas/perso/azure-mlops-helper/tests/test_deploy_aml_model.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/vorph/miniconda3/envs/mlops/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_deploy_aml_model.py:4: in &lt;module&gt;
    from azure_helper.steps.deploy_aml_model import DeploymentSettings, DeployModel
E   ModuleNotFoundError: No module named 'azure_helper.steps.deploy_aml_model'</error></testcase></testsuite></testsuites>
